{{- $quickLinkLables := include "edp-install.labels" . -}}
{{- range $key, $value := index .Values.extraQuickLinks }}
---
{{- range $elem, $elemVal := $value }}
apiVersion: v2.edp.epam.com/v1
kind: QuickLink
metadata:
  labels:
    {{- $quickLinkLables | nindent 4 }}
  name: {{ $elem }}
spec:
  type: "default"
  url: {{ .url }}
  visible: {{ .visible }}
  icon: {{ .icon }}
{{ end }}
{{ end }}
