site_name: EPAM Delivery Platform
repo_name: "epam/edp-install"
repo_url: https://github.com/epam/edp-install
site_url: https://epam.github.io/edp-install


# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - mdx_truly_sane_lists
  - meta
  - toc:
      permalink: true

theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material

  palette:
    primary: "cyan"
    accent: "blue"

  features:
    - navigation.sections

  include_sidebar: true

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

nav:
  - Overview: index.md
  - glossary.md
  - getting_started.md
  - Operator Guide:
    - operator-guide/index.md
    - Enable IRSA (AWS): operator-guide/aws-irsa.md
    - operator-guide/add-other-code-language.md
    - Jira Integration:
      - Overview: operator-guide/jira-integration.md
      - operator-guide/jira-gerrit-integration.md
    - operator-guide/import-strategy.md
    - GitHub Integration:
      - Overview: operator-guide/github-integration.md
    - GitLab Integration:
      - Overview: operator-guide/gitlab-integration.md
      - operator-guide/gitlabci-integration.md
  - User Guide:
    - user-guide/index.md
    - Application:
      - Overview: user-guide/application.md
      - user-guide/add-application.md
    - Autotest:
      - Overview: user-guide/autotest.md
      - user-guide/add-autotest.md
    - CD pipeline:
      - user-guide/add-cd-pipeline.md
    - Library:
      - Overview: user-guide/library.md
      - user-guide/add-library.md
    - user-guide/pipeline-stages.md
    - user-guide/d-d-diagram.md
  - Developer Guide:
    - developer-guide/index.md
    - developer-guide/local-development.md
    - developer-guide/rest-api.md
  - Releases ⧉: https://github.com/epam/edp-install/releases
