site_name: EPAM Delivery Platform
repo_name: "GitHub"
repo_url: https://github.com/epam/edp-install
site_url: https://epam.github.io/edp-install
edit_uri: ""

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - mdx_truly_sane_lists
  - meta
  - toc:
      permalink: true

theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material

  palette:
    - scheme: default
      primary: cyan
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    - navigation.sections

  include_sidebar: true

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-7ZV6PJ2LSP

nav:
  - Overview: index.md
  - glossary.md
  - getting_started.md
  - Operator Guide:
    - operator-guide/index.md
    - Enable IRSA (AWS): operator-guide/aws-irsa.md
    - operator-guide/add-other-code-language.md
    - Jira Integration:
      - Overview: operator-guide/jira-integration.md
      - operator-guide/jira-gerrit-integration.md
    - operator-guide/import-strategy.md
    - GitHub Integration:
      - Overview: operator-guide/github-integration.md
    - GitLab Integration:
      - Overview: operator-guide/gitlab-integration.md
      - operator-guide/gitlabci-integration.md
  - User Guide:
    - user-guide/index.md
    - Application:
      - Overview: user-guide/application.md
      - user-guide/add-application.md
    - Autotest:
      - Overview: user-guide/autotest.md
      - user-guide/add-autotest.md
      - user-guide/run-functional-autotest.md
    - Library:
      - Overview: user-guide/library.md
      - user-guide/add-library.md
    - Pipelines:
      - Overview: user-guide/pipeline-framework.md
      - Add custom pipline library: user-guide/add-custom-global-pipeline-lib.md
      - CI pipeline:
        - user-guide/customize-ci-pipeline.md
        - Stages:
          - Overview: user-guide/pipeline-stages.md
          - Dockerfile: user-guide/dockerfile-stages.md
          - ECR-to-DockerHub: user-guide/ecr-to-docker-stages.md
          - Helm: user-guide/helm-stages.md
          - Open Policy Agent: user-guide/opa-stages.md
          - Terraform: user-guide/terraform-stages.md
      - CD pipeline:
        - user-guide/add-cd-pipeline.md
        - user-guide/customize-cd-pipeline.md
    - user-guide/d-d-diagram.md
  - Developer Guide:
    - developer-guide/index.md
    - developer-guide/local-development.md
    - developer-guide/rest-api.md
  - Releases ⧉: https://github.com/epam/edp-install/releases
