site_name: EPAM Delivery Platform
repo_url: https://github.com/epam/edp-install
site_url: https://epam.github.io/edp-install
edit_uri: ""
site_description: EPAM Delivery Platform is a cloud-native solution for software delivery automation. It offers various tools and features for creating, managing, and deploying applications.

# Copyright
copyright: Copyright &copy; 2018 - 2023 EPAM Delivery Platform -
  <a href="#__consent">Change cookie settings</a>

# Extensions
markdown_extensions:
  - footnotes
  - fancyboxmd
  - admonition
  - attr_list
  - codehilite
  - mdx_truly_sane_lists
  - meta
  - toc:
      permalink: ⚓︎
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - https://unpkg.com/mermaid@8.14.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.6/lottie.min.js
  - overrides/animation.js

theme:
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material

  palette:
    - scheme: default
      primary: cyan
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - awesome-pages
  - meta-descriptions:
      trim: true
  - mkdocs-video
  - search
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        headlamp-user-guide/index.md: user-guide/index.md
        headlamp-user-guide/marketplace.md: user-guide/marketplace.md
        headlamp-user-guide/add-marketplace.md: user-guide/add-marketplace.md
        headlamp-user-guide/add-application.md: user-guide/add-application.md
        headlamp-user-guide/application.md: user-guide/application.md
        headlamp-user-guide/add-autotest.md: user-guide/add-autotest.md
        headlamp-user-guide/autotest.md: user-guide/autotest.md
        headlamp-user-guide/add-library.md: user-guide/add-library.md
        headlamp-user-guide/library.md: user-guide/library.md
        headlamp-user-guide/add-infrastructure.md: user-guide/add-infrastructure.md
        headlamp-user-guide/infrastructure.md: user-guide/infrastructure.md
        headlamp-user-guide/manage-branches.md: user-guide/manage-branches.md
        headlamp-user-guide/add-cd-pipeline.md: user-guide/add-cd-pipeline.md
        headlamp-user-guide/add-quality-gate.md: user-guide/add-quality-gate.md
        headlamp-user-guide/add-git-server.md: user-guide/add-git-server.md
        headlamp-user-guide/git-server-overview.md: user-guide/git-server-overview.md
        headlamp-user-guide/add-cluster.md: user-guide/add-cluster.md
        headlamp-user-guide/cluster.md: user-guide/cluster.md
        operator-guide/upgrade-edp-2.7.8-to-2.8.4.md: operator-guide/upgrade-edp-2.8.md
        operator-guide/upgrade-edp-2.8.4-to-2.9.0.md: operator-guide/upgrade-edp-2.9.md
        operator-guide/upgrade-edp-2.10.x-to-2.11.x.md: operator-guide/upgrade-edp-2.11.md
        operator-guide/upgrade-edp-2.11.x-to-2.12.x.md: operator-guide/upgrade-edp-2.12.md
        operator-guide/upgrade-keycloak-17.0.x-legacy-to-19.0.x.md: operator-guide/upgrade-keycloak-19.0.md

extra:
  analytics:
    provider: google
    property: G-7ZV6PJ2LSP
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@theplatformteam
    - icon: fontawesome/brands/medium
      link: https://medium.com/epam-delivery-platform
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/epamedp
    - icon: fontawesome/solid/paper-plane
      link: mailto:SupportEPMD-EDP@epam.com

  consent:
    actions:
      - accept
      - reject
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav:
  - Home: index.md
  - Getting Started:
    - overview.md
    - features.md
    - getting-started.md
    - glossary.md
    - supported-versions.md
  - Operator Guide:
    - operator-guide/index.md
    - Installation:
      - Prerequisites:
        - Overview: operator-guide/prerequisites.md
        - Set Up Kubernetes: operator-guide/kubernetes-cluster-settings.md
        - Set Up OpenShift: operator-guide/openshift-cluster-settings.md
        - Install NGINX Ingress Controller: operator-guide/install-ingress-nginx.md
        - Install Keycloak: operator-guide/install-keycloak.md
        - Install DefectDojo: operator-guide/install-defectdojo.md
        - Install ReportPortal: operator-guide/install-reportportal.md
        - Install Argo CD: operator-guide/install-argocd.md
        - Install Tekton: operator-guide/install-tekton.md
        - Multi-Tenancy:
          - Capsule: operator-guide/capsule.md
          - Kiosk:
              - EDP Kiosk Usage: operator-guide/edp-kiosk-usage.md
              - Set Up Kiosk: operator-guide/install-kiosk.md
        - Install Harbor: operator-guide/install-harbor.md
      - Install EDP: operator-guide/install-edp.md
      - Install via Helmfile: operator-guide/install-via-helmfile.md
      - Install via AWS Marketplace: operator-guide/aws-marketplace-install.md
    - Configuration:
      - EDP Access Model: operator-guide/edp-access-model.md
      # - Add Other Code Language: operator-guide/add-other-code-language.md
      - Version Control Systems:
        - Overview: operator-guide/vcs.md
        - Integrate GitHub/GitLab in Tekton: operator-guide/import-strategy-tekton.md
      - Headlamp OIDC: operator-guide/headlamp-oidc.md
      - Manage Namespace: operator-guide/namespace-management.md
      - EKS OIDC Integration: operator-guide/eks-oidc-integration.md
      - Jira:
        - Adjust Jira Integration: operator-guide/jira-integration.md
        - Adjust VCS Integration With Jira: operator-guide/jira-gerrit-integration.md
    - Integration:
      - Cluster Add-Ons: operator-guide/add-ons-overview.md
      - Tekton:
          - Overview: operator-guide/tekton-overview.md
          - Monitoring: operator-guide/tekton-monitoring.md
          - MS Teams Notification: operator-guide/notification-msteams.md
      - Container Registry:
          - Harbor:
              - Harbor Integration: operator-guide/container-registry-harbor-integration-tekton-ci.md
              - OIDC in Harbor: operator-guide/harbor-oidc.md
      - AWS Integration:
        - Configure AWS WAF With Terraform: operator-guide/waf-tf-configuration.md
        - Install Amazon EBS CSI Driver: operator-guide/ebs-csi-driver.md
        - Associate IAM Roles With Service Accounts: operator-guide/enable-irsa.md
        - IAM Roles for Kaniko Service Accounts: operator-guide/kaniko-irsa.md
        - IAM Roles for Velero Service Accounts: operator-guide/velero-irsa.md
        - IAM Roles for Loki Service Accounts: operator-guide/loki-irsa.md
        - EKS OIDC With Keycloak: operator-guide/configure-keycloak-oidc-eks.md
      - ReportPortal:
          - Keycloak Integration: operator-guide/reportportal-keycloak.md
          - Integration With Tekton: operator-guide/report-portal-integration-tekton.md
      - Logsight Integration: operator-guide/logsight-integration.md
      - DependencyTrack: operator-guide/dependency-track.md
      - SonarQube: operator-guide/sonarqube.md
      - Nexus Sonatype: operator-guide/nexus-sonatype.md
    - Platform Capabilities:
      - GitOps:
        - Argo CD Integration: operator-guide/argocd-integration.md
      - Secrets Management:
        - Install External Secrets Operator: operator-guide/install-external-secrets-operator.md
        - External Secrets Operator Integration: operator-guide/external-secrets-operator-integration.md
      - DevSecOps:
        - Secure Delivery: operator-guide/overview-devsecops.md
        - Verification of EDP Artifacts: operator-guide/artifacts-verification.md
      - Backup With Velero:
          - Install Velero: operator-guide/install-velero.md
          - Restore EDP Tenant With Velero: operator-guide/restore-edp-with-velero.md
      - Logging:
          - Install Grafana Loki: operator-guide/install-loki.md
          - Multitenant Logging: operator-guide/multitenant-logging.md
          - Schedule Pods Restart: operator-guide/schedule-pods-restart.md
          - Aggregate Application Logs Using EFK Stack: operator-guide/kibana-ilm-rollover.md
      - Manage Custom Certificates: operator-guide/manage-custom-certificate.md
      - Single Sign-on:
          - Protect Endpoints: operator-guide/oauth2-proxy.md
    - Upgrade:
      - EDP:
          - v3.4 to 3.5: operator-guide/upgrade-edp-3.5.md
          - v3.3 to 3.4: operator-guide/upgrade-edp-3.4.md
          - v3.2 to 3.3: operator-guide/upgrade-edp-3.3.md
          - v3.1 to 3.2: operator-guide/upgrade-edp-3.2.md
          - Older Versions:
            - v3.0 to 3.1: operator-guide/upgrade-edp-3.1.md
            - v2.12 to 3.0: operator-guide/upgrade-edp-3.0.md
            - v2.11 to 2.12: operator-guide/upgrade-edp-2.12.md
            - v2.10 to 2.11: operator-guide/upgrade-edp-2.11.md
            - v2.9 to 2.10: operator-guide/upgrade-edp-2.10.md
            - v2.8 to 2.9: operator-guide/upgrade-edp-2.9.md
            - v2.7 to 2.8: operator-guide/upgrade-edp-2.8.md
      - Keycloak:
          - v17.0 to 19.0: operator-guide/upgrade-keycloak-19.0.md
    - Tutorials:
      - CI Pipelines for Terraform: user-guide/terraform-stages.md
      - Deploy AWS EKS Cluster: operator-guide/deploy-aws-eks.md
      - Deploy OKD 4.9 Cluster: operator-guide/deploy-okd.md
      - Deploy OKD 4.10 Cluster: operator-guide/deploy-okd-4.10.md
      - Use Cert-Manager in OpenShift: operator-guide/ssl-automation-okd.md
      - Migrate CI Pipelines From Jenkins to Tekton: operator-guide/migrate-ci-pipelines-from-jenkins-to-tekton.md
      - Uninstall EDP: operator-guide/delete-edp.md
  - User Guide:
    - user-guide/index.md
    - Marketplace:
        - Marketplace Overview: user-guide/marketplace.md
        - user-guide/add-marketplace.md
    - Components:
      - user-guide/components.md
      - Application:
          - user-guide/add-application.md
          - Manage Applications: user-guide/application.md
      - Autotest:
          - user-guide/add-autotest.md
          - Manage Autotests: user-guide/autotest.md
      - Library:
          - user-guide/add-library.md
          - Manage Libraries: user-guide/library.md
      - Infrastructure:
          - user-guide/add-infrastructure.md
          - Manage Infrastructures: user-guide/infrastructure.md
      - Manage Branches: user-guide/manage-branches.md
    - Environments:
        - user-guide/add-cd-pipeline.md
        - user-guide/manage-environments.md
        - user-guide/add-quality-gate.md
    - Configuration:
      - Git Server:
          #- user-guide/add-git-server.md
          - Manage Git Servers: user-guide/git-server-overview.md
      - Cluster:
          - user-guide/add-cluster.md
          - Manage Clusters: user-guide/cluster.md
      - GitOps:
          - user-guide/gitops.md
  - Developer Guide:
    - developer-guide/index.md
    - developer-guide/local-development.md
    - developer-guide/mk-docs-development.md
    - developer-guide/edp-workflow.md
  - Use Cases:
    - use-cases/index.md
    - Scaffold and Deploy FastAPI Application: use-cases/application-scaffolding.md
    - Deploy Application With Custom Build Tool/Framework: use-cases/tekton-custom-pipelines.md
    - Secured Secrets Management for Application Deployment: use-cases/external-secrets.md
    - Autotest as a Quality Gate: use-cases/autotest-as-quality-gate.md
  - FAQ: faq.md
  - RoadMap: roadmap.md
  - Releases ⧉: https://github.com/epam/edp-install/blob/master/RELEASES.md
