site_name: EPAM Delivery Platform
repo_name: "GitHub"
repo_url: https://github.com/epam/edp-install
site_url: https://epam.github.io/edp-install
edit_uri: ""

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - mdx_truly_sane_lists
  - meta
  - toc:
      permalink: ⚓︎

theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material

  palette:
    - scheme: default
      primary: cyan
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-7ZV6PJ2LSP
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/epamedp

nav:
  - Overview: index.md
  - features.md
  - Getting Started: getting-started.md
  - Operator Guide:
    - operator-guide/index.md
    - Installation:
      - Prerequisites:
        - Install Ingress-nginx: operator-guide/install-ingress-nginx.md
        - Install Keycloak: operator-guide/install-keycloak.md
        - Kiosk:
            - EDP Kiosk Usage: operator-guide/edp-kiosk-usage.md
            - Set Up Kiosk: operator-guide/install-kiosk.md
        - Set Up Kubernetes: operator-guide/kubernetes-cluster-settings.md
        - Set Up OpenShift: operator-guide/openshift-cluster-settings.md
      - Install EDP: operator-guide/install-edp.md
    - Configuration:
      - Add Other Code Language: operator-guide/add-other-code-language.md
      - Backup With Velero:
          - Install Velero: operator-guide/install-velero.md
          - Restore EDP Tenant With Velero: operator-guide/restore-edp-with-velero.md
      - Enable VCS Import Strategy: operator-guide/import-strategy.md
      - Manage Jenkins Pipelines:
        - Overview: operator-guide/overview-manage-jenkins-pipelines.md
        - Manage Jenkins CI Pipeline Job Provisioner: operator-guide/manage-jenkins-ci-job-provision.md
        - Manage Jenkins CD Pipeline Job Provisioner: operator-guide/manage-jenkins-cd-job-provision.md
        - Delete Jenkins Job Provision: operator-guide/delete-jenkins-job-provision.md
      - Logging:
          - Install Grafana Loki: operator-guide/install-loki.md
          - Schedule Pods Restart: operator-guide/schedule-pods-restart.md
    - Integration:
      - AWS Integration:
        - Associate IAM Roles With Service Accounts: operator-guide/enable-irsa.md
        - IAM Roles for Kaniko Service Accounts: operator-guide/kaniko-irsa.md
        - IAM Roles for Velero Service Accounts: operator-guide/velero-irsa.md
        - IAM Roles for Loki Service Accounts: operator-guide/loki-irsa.md
      - Jira Integration:
          - Adjust Jira Integration: operator-guide/jira-integration.md
          - Adjust VCS Integration With Jira: operator-guide/jira-gerrit-integration.md
      - GitHub Integration: operator-guide/github-integration.md
      - GitLab Integration:
          - GitLab Integration: operator-guide/gitlab-integration.md
          - Adjust GitLab CI Tool: operator-guide/gitlabci-integration.md
      - Perf Server Integration: operator-guide/perf-integration.md
    - Upgrade:
      - EDP on Kubernetes:
          - Upgrade EDP v.2.7.8 to v.2.8.4: operator-guide/upgrade-edp-2.7.8-to-2.8.4.md
          - Upgrade EDP v.2.8.4 to v.2.9.0: operator-guide/upgrade-edp-2.8.4-to-2.9.0.md
          - Upgrade EDP v.2.9.0 to v.2.10.1: operator-guide/upgrade-edp-2.9.0-to-2.10.1.md
    - Tutorials:
        - Deploy AWS EKS Cluster: operator-guide/deploy-aws-eks.md
        - Manage Jenkins Agent: operator-guide/add-jenkins-agent.md
  - User Guide:
    - user-guide/index.md
    - Application:
      - Overview: user-guide/application.md
      - user-guide/add-application.md
    - Autotest:
      - Overview: user-guide/autotest.md
      - user-guide/add-autotest.md
    - Library:
      - Overview: user-guide/library.md
      - user-guide/add-library.md
    - Pipelines:
      - EDP CI/CD Overview: user-guide/cicd-overview.md
      - EDP Pipeline Framework: user-guide/pipeline-framework.md
      - Add Custom Pipeline Library: user-guide/add-custom-global-pipeline-lib.md
      - CI Pipeline:
        - user-guide/ci-pipeline-details.md
        - user-guide/code-review-pipeline.md
        - user-guide/build-pipeline.md
        - user-guide/customize-ci-pipeline.md
        - Stages:
          - Overview: user-guide/pipeline-stages.md
          - Dockerfile: user-guide/dockerfile-stages.md
          - ECR-to-DockerHub: user-guide/ecr-to-docker-stages.md
          - Helm: user-guide/helm-stages.md
          - Open Policy Agent: user-guide/opa-stages.md
          - Terraform: user-guide/terraform-stages.md
      - CD Pipeline:
        - user-guide/cd-pipeline-details.md
        - user-guide/add-cd-pipeline.md
        - user-guide/customize-cd-pipeline.md
        - user-guide/prepare-for-release.md
    - user-guide/d-d-diagram.md
  - Developer Guide:
    - developer-guide/index.md
    - developer-guide/local-development.md
    - developer-guide/rest-api.md
    - developer-guide/mk-docs-development.md
    - developer-guide/edp-workflow.md
  - RoadMap: roadmap.md
  - Use Cases:
    - use-cases/index.md
    - Autotest as Quality Gate: use-cases/autotest-as-quality-gate.md
    - Promote Application in CD Pipeline: use-cases/promotion-procedure.md
  - FAQ: faq.md
  - glossary.md
  - Releases ⧉: https://github.com/epam/edp-install/blob/master/RELEASES.md
