site_name: EPAM Delivery Platform
repo_url: https://github.com/epam/edp-install
site_url: https://epam.github.io/edp-install
edit_uri: ""
site_description: EPAM Delivery Platform

# Copyright
copyright: Copyright &copy; 2018 - 2023 EPAM Delivery Platform -
  <a href="#__consent">Change cookie settings</a>

# Extensions
markdown_extensions:
  - footnotes
  - fancyboxmd
  - admonition
  - attr_list
  - codehilite
  - mdx_truly_sane_lists
  - meta
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
  - toc:
      permalink: ⚓︎
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite

extra_css:
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - https://unpkg.com/mermaid@8.14.0/dist/mermaid.min.js

theme:
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material

  palette:
    - scheme: default
      primary: cyan
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - mkdocs-video
  - search
  - awesome-pages
  - charts
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-7ZV6PJ2LSP
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@theplatformteam
    - icon: fontawesome/brands/medium
      link: https://medium.com/epam-delivery-platform
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/epamedp
    - icon: fontawesome/solid/paper-plane
      link: mailto:SupportEPMD-EDP@epam.com

  consent:
    actions:
      - accept
      - reject
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav:
  - Home: index.md
  - Getting Started:
    - overview.md
    - features.md
    - getting-started.md
    - glossary.md
    - supported-versions.md
  - Operator Guide:
    - operator-guide/index.md
    - Installation:
      - Prerequisites:
        - Overview: operator-guide/prerequisites.md
        - Set Up Kubernetes: operator-guide/kubernetes-cluster-settings.md
        - Set Up OpenShift: operator-guide/openshift-cluster-settings.md
        - Install NGINX Ingress Controller: operator-guide/install-ingress-nginx.md
        - Install Keycloak: operator-guide/install-keycloak.md
        - Install DefectDojo: operator-guide/install-defectdojo.md
        - Install ReportPortal: operator-guide/install-reportportal.md
        - Install Argo CD: operator-guide/install-argocd.md
        - Install Tekton: operator-guide/install-tekton.md
        - Kiosk:
            - EDP Kiosk Usage: operator-guide/edp-kiosk-usage.md
            - Set Up Kiosk: operator-guide/install-kiosk.md
      - Install EDP: operator-guide/install-edp.md
      - Install via Helmfile: operator-guide/install-via-helmfile.md
    - Configuration:
      - Add Other Code Language: operator-guide/add-other-code-language.md
      - Enable VCS Import Strategy: operator-guide/import-strategy.md
      - Manage Jenkins Pipelines:
        - Overview: operator-guide/overview-manage-jenkins-pipelines.md
        - Manage Jenkins CI Pipeline Job Provisioner: operator-guide/manage-jenkins-ci-job-provision.md
        - Manage Jenkins CD Pipeline Job Provisioner: operator-guide/manage-jenkins-cd-job-provision.md
        - Delete Jenkins Job Provision: operator-guide/delete-jenkins-job-provision.md
      - Headlamp OIDC: operator-guide/headlamp-oidc.md
    - Integration:
      - Tekton:
          Overview: operator-guide/tekton-overview.md
          Monitoring: operator-guide/tekton-monitoring.md
      - AWS Integration:
        - Configure AWS WAF With Terraform: operator-guide/waf-tf-configuration.md
        - Install Amazon EBS CSI Driver: operator-guide/ebs-csi-driver.md
        - Associate IAM Roles With Service Accounts: operator-guide/enable-irsa.md
        - IAM Roles for Kaniko Service Accounts: operator-guide/kaniko-irsa.md
        - IAM Roles for Velero Service Accounts: operator-guide/velero-irsa.md
        - IAM Roles for Loki Service Accounts: operator-guide/loki-irsa.md
        - EKS OIDC With Keycloak: operator-guide/configure-keycloak-oidc-eks.md
      - Jira Integration:
          - Adjust Jira Integration: operator-guide/jira-integration.md
          - Adjust VCS Integration With Jira: operator-guide/jira-gerrit-integration.md
      - GitHub Integration:
          - GitHub Integration: operator-guide/github-integration.md
          - Debug GitHub Webhooks in Jenkins: operator-guide/github-debug-webhooks.md
      - GitLab Integration:
          - GitLab Integration: operator-guide/gitlab-integration.md
          - Adjust GitLab CI Tool: operator-guide/gitlabci-integration.md
          - Debug GitLab Webhooks in Jenkins: operator-guide/gitlab-debug-webhooks.md
      - Perf Server Integration: operator-guide/perf-integration.md
      - ReportPortal:
          - Keycloak Integration: operator-guide/reportportal-keycloak.md
          - Integration With Tekton: operator-guide/report-portal-integration-tekton.md
      - Logsight Integration: operator-guide/logsight-integration.md
    - Platform Capabilities:
      - GitOps:
        - Argo CD Integration: operator-guide/argocd-integration.md
      - Secrets Management:
        - Install External Secrets Operator: operator-guide/install-external-secrets-operator.md
        - External Secrets Operator Integration: operator-guide/external-secrets-operator-integration.md
      - Static Application Security Testing:
          - Static Application Security Testing Overview: operator-guide/overview-sast.md
          - Scanners:
              - Add Security Scanner: operator-guide/add-security-scanner.md
              - Semgrep: operator-guide/sast-scaner-semgrep.md
      - Backup With Velero:
          - Install Velero: operator-guide/install-velero.md
          - Restore EDP Tenant With Velero: operator-guide/restore-edp-with-velero.md
      - Logging:
          - Install Grafana Loki: operator-guide/install-loki.md
          - Multitenant Logging: operator-guide/multitenant-logging.md
          - Schedule Pods Restart: operator-guide/schedule-pods-restart.md
      - Manage Custom Certificates: operator-guide/manage-custom-certificate.md
      - Single Sign-on:
          - Protect Endpoints: operator-guide/oauth2-proxy.md
    - Upgrade:
      - EDP:
          - v3.0 to 3.1: operator-guide/upgrade-edp-3.1.md
          - v2.12 to 3.0: operator-guide/upgrade-edp-3.0.md
          - v2.11 to 2.12: operator-guide/upgrade-edp-2.12.md
          - Older Versions:
            - v2.10 to 2.11: operator-guide/upgrade-edp-2.11.md
            - v2.9 to 2.10: operator-guide/upgrade-edp-2.10.md
            - v2.8 to 2.9: operator-guide/upgrade-edp-2.9.md
            - v2.7 to 2.8: operator-guide/upgrade-edp-2.8.md
      - Keycloak:
          - v17.0 to 19.0: operator-guide/upgrade-keycloak-19.0.md
    - Tutorials:
      - Deploy AWS EKS Cluster: operator-guide/deploy-aws-eks.md
      - Deploy OKD 4.9 Cluster: operator-guide/deploy-okd.md
      - Deploy OKD 4.10 Cluster: operator-guide/deploy-okd-4.10.md
      - Use Cert-Manager in OpenShift: operator-guide/ssl-automation-okd.md
      - Manage Jenkins Agent: operator-guide/add-jenkins-agent.md
#  - User Guide:
#    - user-guide/index.md
#    - Application:
#      - Overview: user-guide/application.md
#      - user-guide/add-application.md
#    - Autotest:
#      - Overview: user-guide/autotest.md
#      - user-guide/add-autotest.md
#    - Library:
#      - Overview: user-guide/library.md
#      - user-guide/add-library.md
#    - Pipelines:
#      - EDP CI/CD Overview: user-guide/cicd-overview.md
#      - EDP Pipeline Framework: user-guide/pipeline-framework.md
#      - Add Custom Pipeline Library: user-guide/add-custom-global-pipeline-lib.md
#      - CI Pipeline:
#        - user-guide/ci-pipeline-details.md
#        - user-guide/code-review-pipeline.md
#        - user-guide/build-pipeline.md
#        - user-guide/customize-ci-pipeline.md
#        - Stages:
#          - Overview: user-guide/pipeline-stages.md
#          - Use Dockerfile Linters for Code Review Pipeline: user-guide/dockerfile-stages.md
#          - Promote Docker Images From ECR to Docker Hub: user-guide/ecr-to-docker-stages.md
#          - Helm Chart Testing and Documentation Tools: user-guide/helm-stages.md
#          - Use Open Policy Agent: user-guide/opa-stages.md
#          - CI Pipeline for Terraform: user-guide/terraform-stages.md
#          - CI Pipeline for Container: user-guide/container-stages.md
#      - CD Pipeline:
#        - user-guide/cd-pipeline-details.md
#        - user-guide/add-cd-pipeline.md
#        - user-guide/customize-cd-pipeline.md
#        - user-guide/prepare-for-release.md
#        - Stages:
#          - Copy Shared Secrets: user-guide/copy-shared-secrets.md
#          - Helm Release Deletion: user-guide/helm-release-deletion.md
#          - Semi Auto Deploy: user-guide/semi-auto-deploy.md
#    - user-guide/d-d-diagram.md
      - Migrate CI Pipelines From Jenkins to Tekton: operator-guide/migrate-ci-pipelines-from-jenkins-to-tekton.md
  - User Guide:
    - headlamp-user-guide/index.md
    - Application:
        - Overview: headlamp-user-guide/application.md
        - headlamp-user-guide/add-application.md
    - Autotest:
        - Overview: headlamp-user-guide/autotest.md
        - headlamp-user-guide/add-autotest.md
    - Library:
        - Overview: headlamp-user-guide/library.md
        - headlamp-user-guide/add-library.md
    - Pipelines:
        - CD Pipeline:
            - headlamp-user-guide/add-cd-pipeline.md
            - headlamp-user-guide/add-quality-gate.md
    - Git Server:
        - headlamp-user-guide/add-git-server.md
  - Developer Guide:
    - developer-guide/index.md
    - developer-guide/local-development.md
    - developer-guide/rest-api.md
    - developer-guide/mk-docs-development.md
    - developer-guide/edp-workflow.md
  - Use Cases:
    - use-cases/index.md
    - Scaffold and Deploy FastAPI Application: use-cases/application-scaffolding.md
    - Autotest as Quality Gate: use-cases/autotest-as-quality-gate.md
    - Deploy Application With Custom Build Tool/Framework: use-cases/tekton-custom-pipelines.md
  - FAQ: faq.md
  - RoadMap: roadmap.md
  - Releases ⧉: https://github.com/epam/edp-install/blob/master/RELEASES.md
