site_name: EPAM Delivery Platform
repo_name: "GitHub"
repo_url: https://github.com/epam/edp-install
site_url: https://epam.github.io/edp-install
edit_uri: ""

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - mdx_truly_sane_lists
  - meta
  - toc:
      permalink: ⚓︎

theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material

  palette:
    - scheme: default
      primary: cyan
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-7ZV6PJ2LSP
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/epamedp

nav:
  - Overview: index.md
  - features.md
  - Getting Started: getting-started.md
  - Operator Guide:
    - operator-guide/index.md
    - Installation:
      - Prerequisites:
        - Ingress-nginx: operator-guide/install-ingress-nginx.md
        - Kiosk: operator-guide/install-kiosk.md
        - Keycloak: operator-guide/install-keycloak.md
        - Kubernetes: operator-guide/kubernetes-cluster-settings.md
        - OpenShift: operator-guide/openshift-cluster-settings.md
      - EDP: operator-guide/install-edp.md
    - Configuration:
      - Add Other Code Language: operator-guide/add-other-code-language.md
      - Manage Jenkins Pipelines:
        - Overview: operator-guide/overview-manage-jenkins-pipelines.md
        - CI Provision: operator-guide/manage-jenkins-ci-job-provision.md
        - CD Provision: operator-guide/manage-jenkins-cd-job-provision.md
        - Delete Job Provision: operator-guide/delete-jenkins-job-provision.md
    - AWS Integration:
      - Associate IAM Roles For Service Accounts (IRSA):
        - Enable IRSA: operator-guide/enable-irsa.md
        - IRSA for Kaniko: operator-guide/kaniko-irsa.md
        - IRSA for Velero: operator-guide/velero-irsa.md
        - IRSA for Loki: operator-guide/loki-irsa.md
    - Jira Integration:
      - Overview: operator-guide/jira-integration.md
      - operator-guide/jira-gerrit-integration.md
    - GitHub Integration:
      - Overview: operator-guide/github-integration.md
    - GitLab Integration:
      - Overview: operator-guide/gitlab-integration.md
      - operator-guide/gitlabci-integration.md
    - Logging Configuration:
      - Install Loki: operator-guide/install-loki.md
    - Schedule pods restart: operator-guide/schedule-pods-restart.md
    - Velero Configuration:
      - Back Up EDP Tenant With Velero:
        - Install Velero: operator-guide/install-velero.md
        - Restore EDP Tenant With Velero: operator-guide/restore-edp-with-velero.md
    - Tutorials:
        - Deploy AWS EKS Cluster: operator-guide/deploy-aws-eks.md
        - Manage Jenkins Agent: operator-guide/add-jenkins-agent.md
  - User Guide:
    - user-guide/index.md
    - Application:
      - Overview: user-guide/application.md
      - user-guide/add-application.md
    - Autotest:
      - Overview: user-guide/autotest.md
      - user-guide/add-autotest.md
      - user-guide/run-functional-autotest.md
    - Library:
      - Overview: user-guide/library.md
      - user-guide/add-library.md
    - Pipelines:
      - Overview: user-guide/pipeline-framework.md
      - Add Custom Pipeline Library: user-guide/add-custom-global-pipeline-lib.md
      - CI pipeline:
        - user-guide/customize-ci-pipeline.md
        - Stages:
          - Overview: user-guide/pipeline-stages.md
          - Dockerfile: user-guide/dockerfile-stages.md
          - ECR-to-DockerHub: user-guide/ecr-to-docker-stages.md
          - Helm: user-guide/helm-stages.md
          - Open Policy Agent: user-guide/opa-stages.md
          - Terraform: user-guide/terraform-stages.md
      - CD pipeline:
        - user-guide/add-cd-pipeline.md
        - user-guide/customize-cd-pipeline.md
    - user-guide/d-d-diagram.md
  - Developer Guide:
    - developer-guide/index.md
    - developer-guide/local-development.md
    - developer-guide/rest-api.md
    - developer-guide/mk-docs-development.md
  - RoadMap: roadmap.md
  - Use Cases: use-cases/index.md
  - glossary.md
  - Releases ⧉: https://github.com/epam/edp-install/releases
