{{- if and .Values.sso.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
    {{- include "edp-install.labels" . | nindent 4 }}
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oauth2-proxy.selectorLabels" . | indent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/oauth2-proxy/configmap.yaml") . | sha256sum }}
      labels:
        app: oauth2-proxy
        {{- include "oauth2-proxy.selectorLabels" . | indent 8 }}
    spec:
      serviceAccountName: oauth2-proxy
      containers:
        - name: oauth2-proxy
          image: "{{ .Values.sso.image.repository }}:{{ .Values.sso.image.tag  }}"
          args:
            - --http-address=0.0.0.0:4180
            - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
          {{- if kindIs "map" .Values.sso.extraArgs }}
            {{- range $key, $value := .Values.sso.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ tpl ($value | toString) $ }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
            {{- end }}
          {{- end }}
          env:
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                # keycloak-client-oauth2-proxy-secret is created by keycloak-operator
                secretKeyRef:
                  name:  keycloak-client-oauth2-proxy-secret
                  key: clientSecret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sso.existingSecret.secretName }}
                  key: {{ .Values.sso.existingSecret.secretKey }}

          {{- if .Values.sso.extraEnv }}
  {{ tpl (toYaml .Values.sso.extraEnv) . | indent 10 }}
          {{- end }}
          ports:
            - containerPort: 4180
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            timeoutSeconds: 5
            successThreshold: 1
            periodSeconds: 10
          resources:
{{ toYaml .Values.sso.resources | indent 12 }}
          volumeMounts:
            - mountPath: /etc/oauth2_proxy/oauth2_proxy.cfg
              name: configmain
              subPath: oauth2_proxy.cfg
          {{- if .Values.sso.extraVolumeMounts }}
            {{- toYaml .Values.sso.extraVolumeMounts | nindent 12 }}
          {{- end }}
      volumes:
        - configMap:
            defaultMode: 420
            name: oauth2-proxy-config
          name: configmain
      {{- if .Values.sso.extraVolumes }}
        {{- toYaml .Values.sso.extraVolumes | nindent 8 }}
      {{- end }}

    {{- if .Values.sso.affinity }}
      affinity:
{{ toYaml .Values.sso.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.sso.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sso.nodeSelector | indent 8 }}
    {{- end }}
      tolerations:
{{ toYaml .Values.sso.tolerations | indent 8 }}
{{ end }}
