apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: fake-db
  name: fake-db
spec:
  replicas: 1
  selector:
    app: fake-db
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: fake-db
    spec:
      containers:
      - name: fake-db
        env:
        - name: POSTGRES_DB
          value: petclinic
        - name: POSTGRES_USER
          value: petclinic
        - name: POSTGRES_PASSWORD
          value: petclinic
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        image: postgres:9.6
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
            protocol: TCP
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 5
      serviceAccount: jenkins