--- # Sonar full installation
- name: "Give rights to sonar account"
  shell: "{{ ocadm }} -n {{ project }} adm policy add-scc-to-user anyuid -z sonar"

- name: "Install Sonar app"
  command: |
    {{ ocadm }} -n {{ project }} new-app -f {{ templates_dir }}/sonar/sonar.yaml 
    -p SONAR_VERSION={{ tools.sonar.version }} 
    -p SONAR_VOLUME_CAPACITY={{ tools.sonar.volume_capacity }} 
    -p SONAR_DB_CAPACITY={{ tools.sonar.volume_db_capacity }}
  register: result
  ignore_errors: true
  changed_when: '"already" not in result.stderr'
  failed_when:
    - 'result.rc != 0'
    - '"already" not in result.stderr'

- name: "Install Sonar-to-Jenkins integration"
  command: "{{ ocadm }} -n {{ project }} new-app -f {{ templates_dir }}/sonar/sonar-integration.yaml"
  register: result
  ignore_errors: true
  changed_when: '"already" not in result.stderr'
  failed_when:
    - 'result.rc != 0'
    - '"already" not in result.stderr'
