--- # This is a structural YAML example to up a master node
- name: "Give rights to gerrit account"
  shell: "{{ ocadm }} -n {{ project }} adm policy add-scc-to-user anyuid -z gerrit"
- name: "Install Gerrit app"
  command: "{{ ocadm }} -n {{ project }} new-app -f {{ templates_dir }}/gerrit/gerrit.yaml -p GERRIT_VERSION={{ tools.gerrit.version }} -p GERRIT_DB_SECRET={{ tools.gerrit.db_secret }} -p GERRIT_DATA_CAPACITY={{ tools.gerrit.volume_capacity }} -p GERRIT_DB_CAPACITY={{ tools.gerrit.volume_db_capacity }} -p GERRIT_WEB_URL={{ tools.gerrit.web_url }} -p GERRIT_MAX_MEMORY={{ tools.gerrit.max_memory }}"
  register: result
  ignore_errors: true
  changed_when: '"already" not in result.stderr'
  failed_when:
    - 'result.rc != 0'
    - '"already" not in result.stderr'
