{{- $argocdDefaultURL := printf "https://argocd.%s" .Values.global.dnsWildCard -}}
{{- if .Values.argocd.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: argocd
spec:
  advancedProtocolMappers: true
  clientId: argocd
  directAccess: true
  public: false
  defaultClientScopes:
    - groups
  targetRealm: {{ .Values.global.edpName }}-main
  webUrl: "{{ .Values.argocd.url | default $argocdDefaultURL }}"
{{- end }}
