{{- $argocdDefaultURL := printf "https://argocd.%s" .Values.global.dnsWildCard -}}
{{- if ne (index .Values "argocd" "enabled") "false" -}}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: argocd
spec:
  advancedProtocolMappers: true
  clientId: argocd
  directAccess: true
  {{ if and .Values.externalSecrets.enabled .Values.externalSecrets.manageEDPInstallSecrets }}
  secret: keycloak-client-argocd-secret
  {{ else if (index .Values "argocd" "oidcSecretName") }}
  secret: {{ (index .Values "argocd" "oidcSecretName") }}
  {{ end }}
  public: false
  defaultClientScopes:
    - groups
  targetRealm: {{ .Values.global.edpName }}-main
  webUrl: "{{ (index .Values "argocd" "url" ) | default $argocdDefaultURL }}"
{{- end }}
