{{- $argocdDefaultURL := printf "https://argocd.%s" .Values.global.dnsWildCard -}}
{{- if .Values.sso.enabled -}}
{{- if .Values.argocd.enabled -}}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: argocd
spec:
  advancedProtocolMappers: true
  clientId: argocd
  directAccess: true
  {{ if and .Values.externalSecrets.enabled .Values.externalSecrets.manageEDPInstallSecrets }}
  secret: keycloak-client-argocd-secret
  {{ else if .Values.argocd.oidcSecretName }}
  secret: {{ .Values.argocd.oidcSecretName }}
  {{ end }}
  public: false
  defaultClientScopes:
    - groups
  targetRealm: {{ .Release.Namespace }}-main
  webUrl: "{{ .Values.argocd.url | default $argocdDefaultURL }}"
{{- end }}
{{- end }}
