apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-deployer
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - list
      - get
      - create
      - watch
      - update
