apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ .Release.Namespace }}-oidc-viewers"
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ .Release.Namespace }}-oidc-developers"
