apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-builder
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ .Release.Namespace }}-oidc-builders"
