{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
groupNames:
  - system:serviceaccounts
kind: ClusterRoleBinding
metadata:
  name: serviceaccounts-registry-viewer
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
roleRef:
  name: registry-viewer
subjects:
  - kind: SystemGroup
    name: system:serviceaccounts
userNames: []
{{end}}