{{- if eq .Values.global.platform "openshift" -}}
  {{- range .Values.edp.adminGroups -}}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{.}}
  labels:
    app.kubernetes.io/name: {{ template "edp-install.fullname" $ }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
users:
  {{ range $.Values.global.admins -}}
  - {{.}}
  {{end}}
{{end}}

  {{- range .Values.edp.developerGroups -}}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{.}}
  labels:
    app.kubernetes.io/name: {{ template "edp-install.fullname" $ }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
users:
  {{ range $.Values.global.developers -}}
  - {{.}}
  {{end}}
  {{end}}
  {{end}}