{{- if eq .Values.global.platform "openshift" -}}
  {{- range .Values.edp.adminGroups -}}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{.}}
  labels:
    {{- include "admin-console-operator.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
users:
      {{ range $.Values.global.admins -}}
  - {{.}}
      {{end}}
    {{end}}
  {{end}}

  {{- range .Values.edp.developerGroups -}}
    {{- if not (lookup "user.openshift.io/v1" "Group" $.Values.global.edpName .)}}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{.}}
users:
      {{ range $.Values.global.developers -}}
  - {{.}}
      {{end}}
  {{end}}
{{end}}