{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
  name: edp-kaniko-registry-editor
roleRef:
  kind: ClusterRole
  name: registry-editor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kaniko-push
{{- end -}}
