{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
groupNames:
  {{- range .Values.edp.adminGroups }}
  - {{. -}}
  {{end}}
kind: RoleBinding
metadata:
  name: developer
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  name: developer
subjects:
  {{- range .Values.edp.adminGroups }}
  - kind: Group
    name: {{. -}}
  {{end}}
userNames: []
{{end}}