{{- if eq .Values.global.platform "openshift" -}}
  {{- range .Values.global.developers -}}
---
apiVersion: user.openshift.io/v1
kind: User
identities: []
groups: []
metadata:
  name: {{.}}
  labels:
    {{- include "admin-console-operator.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{end}}
{{end}}
