{{- if not (or .Values.kaniko.existingDockerConfig .Values.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: kaniko-docker-config
  namespace: {{ .Values.global.edpName }}
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
data:
  config.json: >-
    ewogICJjcmVkc1N0b3JlIjogImVjci1sb2dpbiIKfQ==
type: Opaque
{{- end }}
