apiVersion: v1
kind: ConfigMap
metadata:
  name: kaniko-template
  namespace: {{ .Values.global.edpName }}
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
data:
  kaniko.json: |
    {
      "apiVersion": "v1",
      "kind": "Pod",
      "metadata": {
        "name": "kaniko"
      },
      "spec": {
        "serviceAccountName": "edp-kaniko",
        "securityContext": {
          "fsGroup": 65534
        },
        "initContainers": [
          {
            "name": "init-kaniko",
            "image": "{{ .Values.kaniko.initImage }}",
            "command": [
              "/bin/sh",
              "-c",
              "for i in 1 2 3 4 5 6; do echo \"Waiting for Dockerfile...\"; sleep 10; if [ -f /tmp/workspace/Dockerfile ]; then exit 0; fi; done; exit 1"
            ],
            "volumeMounts": [
              {
                "name": "shared-volume",
                "mountPath": "/tmp/workspace"
              }
            ]
          },
          {
            "name": "init-repository",
            "image": "{{ .Values.kaniko.awsCliImage }}",
            "command": [
              "/bin/sh",
              "-c",
              "aws ecr describe-repositories --repository-names ${REPO_NAME} || aws ecr create-repository --repository-name ${REPO_NAME} || true"
            ],
            "env": [
              {
                "name": "REPO_NAME",
                "value": "REPLACE_REPO_VALUE"
              }
            ]
          }
        ],
        "containers": [
          {
            "name": "kaniko",
            "image": "{{ .Values.kaniko.image }}",
            "args": [
              "--destination=REPLACE_DESTINATION_IMAGE"
            ],
            "volumeMounts": [
              {
                "name": "shared-volume",
                "mountPath": "/workspace"
              },
              {
                "name": "docker-registry-config",
                "mountPath": "/kaniko/.docker/"
              }
            ]
          }
        ],
        "restartPolicy": "Never",
        "volumes": [
          {
            "name": "shared-volume",
            "emptyDir": {}
          },
          {
            "name": "docker-registry-config",
            "secret": {
              {{- if .Values.kaniko.existingDockerConfig }}
              "secretName": "{{ .Values.kaniko.existingDockerConfig }}"
              {{- else }}
              "secretName": "kaniko-docker-config"
              {{- end }}
            }
          }
        ]
      }
    }
