---
- name: "Get JSON with environments configuration"
  command: |
    {{ ocadm }} -n {{ project_cicd }} get cm project-settings -o jsonpath='{.data.env\.settings\.json}'
  register: env_config

- set_fact:
     env_settings_json: "{{ env_config.stdout | from_json }}"

- debug:
    msg: "Found environment: {{ item | lower }}"
  with_items: " {{ env_settings_json.keys() }} "

- name: "Create projects in Openshift"
  command: "{{ ocadm }} new-project {{ item | lower }}"
  with_items: " {{ env_settings_json.keys() }} "

- name: "Define access to admin for new projects "
  command: "{{ ocadm }} adm policy add-role-to-user admin admin -n {{ item | lower }}"
  with_items: " {{ env_settings_json.keys() }} "

- name: "Define access to jenkins for new projects "
  command: "{{ ocadm }} adm policy add-role-to-user system:serviceaccount:{{ project_cicd }}:jenkins admin -n {{ item | lower }}"
  with_items: " {{ env_settings_json.keys() }} "
