kind: Template
apiVersion: v1
metadata:
  name: edp
  annotations:
    description: |-
          Template for deploying EPAM Delivery Platform (EDP) aka "The Rocket" tools
    openshift.io/display-name: EDP - The Rocket
    template.openshift.io/provider-display-name: EPAM
    template.openshift.io/support-url: https://www.epam.com
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: edp-deploy-${PROJECTS_PREFIX}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: edp-deploy
      spec:
        restartPolicy: Never
        serviceAccount: edp
        containers:
        - image: ${EDP_VERSION}
          imagePullPolicy: IfNotPresent
          name: edp-deploy
          command:
            - "ansible-playbook"
            - "-v"
            - "-i"
            - "localhost,"
            - "-e project=${PROJECTS_PREFIX}"
            - "-e ocadm=oc"
            - "-e ansible_connection=local"
            - "-e gerrit_version=${GERRIT_VERSION}"
            - "-e gerrit_volume_capacity=${GERRIT_DATA_CAPACITY}"
            - "-e gerrit_volume_db_capacity=${GERRIT_DB_CAPACITY}"
            - "-e gerrit_web_url=${GERRIT_WEB_URL}"
            - "-e gerrit_job_version=${GERRIT_JOB_VERSION}"
            - "-e jenkins_enable_oauth=${JENKINS_ENABLE_OAUTH}"
            - "-e jenkins_volume_capacity=${JENKINS_VOLUME_CAPACITY}"
            - "-e jenkins_maven_cache_volume_capacity=${JENKINS_MAVEN_CACHE_VOLUME_CAPACITY}"
            - "-e jenkins_frontend_image=${JENKINS_FRONTEND_IMAGE}"
            - "-e jenkins_backend_image=${JENKINS_BACKEND_IMAGE}"
            - "-e nexus_version=${NEXUS_VERSION}"
            - "-e nexus_volume_capacity=${NEXUS_VOLUME_CAPACITY}"
            - "-e sonar_version=${SONAR_VERSION}"
            - "-e sonar_volume_capacity=${SONAR_VOLUME_CAPACITY}"
            - "-e sonar_volume_db_capacity=${SONAR_DB_CAPACITY}"
            - "install/deploy_ci_tools/install.yml"
parameters:
- displayName: Image of EDP container
  description: Image and tag that defines version of EDP that will be deployed
  name: EDP_VERSION
  value: "docker-registry-default.main.edp.projects.epam.com/infra/edp-test:test"
- displayName: Prefix for projects
  description: Prefix that will be added to projects created by EDP Platform
  name: PROJECTS_PREFIX
  value: "test"
#Gerrit parameters
- displayName: Gerrit version
  value: "2.14.1"
  name: GERRIT_VERSION
- displayName: Gerrit Volume Capacity
  description: Volume space available for Gerrit data
  name: GERRIT_DATA_CAPACITY
  value: 5Gi
  required: true
- displayName: Gerrit database Volume Capacity
  description: Volume space available for Gerrit DB
  name: GERRIT_DB_CAPACITY
  value: 5Gi
  required: true
- displayName: Gerrit WEB URL
  description: Gerrit WEB URL is needed for authentication purposes
  name: GERRIT_WEB_URL
  value: 'http://gerrit.main.edp.projects.epam.com'
- displayName: Gerrit job version
  value: "docker-registry-default.main.edp.projects.epam.com/infra/gerrit-job:latest"
  name: GERRIT_JOB_VERSION
#Jenkins parameters
- displayName: Enable OAuth in Jenkins
  description: Whether to enable OAuth OpenShift integration. If false, the static
    account 'admin' will be initialized with the password 'password'.
  displayName: Enable OAuth in Jenkins
  name: JENKINS_ENABLE_OAUTH
  value: "false"
- displayName: Volume Capacity
  description: Volume space available for Jenkins data
  name: JENKINS_VOLUME_CAPACITY
  value: 10Gi
  required: true
- displayName: Maven Cache Volume Capacity
  description: Volume space available for maven cache data
  name: JENKINS_MAVEN_CACHE_VOLUME_CAPACITY
  required: true
  value: 10Gi
- displayName: Frontend docker image.
  name: JENKINS_FRONTEND_IMAGE
  value: "docker-registry-default.main.edp.projects.epam.com/infra/ui-slave:latest"
- displayName: Backend docker image.
  name: JENKINS_BACKEND_IMAGE
  value: "openshift/jenkins-slave-maven-centos7"
#Nexus parameters
- displayName: Sonatype Nexus version
  name: NEXUS_VERSION
  value: "3.6.2"
- displayName: Volume Space for Nexus
  description: Volume space available for Sonatype Nexus data
  name: NEXUS_VOLUME_CAPACITY
  value: 5Gi
#Sonar parameters
- displayName: SonarQube version
  value: "6.7"
  name: SONAR_VERSION
- description: Volume space available for SonarQube
  displayName: SonarQube Volume Capacity
  name: SONAR_VOLUME_CAPACITY
  value: 5Gi
- description: Volume space available for SonarQube Database
  displayName: SonarQube database Volume Capacity
  name: SONAR_DB_CAPACITY
  value: 5Gi