{{- if .Values.global.database.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.global.database.name}}
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: db
      port: {{.Values.global.database.port}}
      protocol: TCP
      targetPort: {{.Values.global.database.port}}
  selector:
    app: {{.Values.global.database.name}}
  type: ClusterIP
{{end}}