{{- if eq .Values.global.platform "openshift" -}}
apiVersion: v1.edp.epam.com/v1alpha1
kind: EDPComponent
metadata:
  name: docker-registry
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: docker-registry
  url: {{ .Values.dockerRegistry.url }}
  visible: false
  icon: stub-value
{{end}}