---
- name: "Login to openshift"
  shell: "{{ ocadm }} login -u system:admin"
  register: can_login
  when: ocadm != "oc"
  
- fail:
    msg: "Sorry, we can't login to the cluster. Check permissions on the cluster's side"
  when: not can_login|skipped and can_login.stdout == "false"

- name: "Check if project edp projects exists"
  shell: bash -c "test \"$(echo $({{ ocadm }} get project | awk '{print $1}' | grep {{ item }}$ | wc -l))\" == \"1\" && echo true || echo false"
  with_items: "{{ projects_list }}"
  register: project_exist
  
- fail:
    msg: "Some of edp projects already exist"
  when: item.stdout == "true"
  with_items: "{{ project_exist.results }}"

- name: "Create project in Openshift, giving rights to admin user on project we've just created"
  shell: "{{ ocadm }} new-project {{ item }} && {{ ocadm }} adm policy add-role-to-user admin admin -n {{ item }}"
  with_items: "{{ projects_list }}"

- name: "Switching to CICD project"
  shell: "{{ ocadm }} project {{ project_cicd }}"

- name: Creates directory for templates
  file: path="{{ templates_dir }}" state=directory

- name: Copying templates of tools
  copy:
    src: "../../../tools/{{ item }}"
    dest: "{{ templates_dir }}"
    force: yes
  with_items:
    - jenkins
    - gerrit
    - nexus
    - sonar
    - edp-cockpit

