--- 
- name: "Login to openshift"
  shell: "{{ ocadm }} login -u system:admin"
  register: can_login
  when: ocadm != "oc"
  
- fail:
    msg: "Sorry, we can't login to the cluster. Check permissions on the cluster's side"
  when: not can_login|skipped and can_login.stdout == "false"

- name: "Check if project {{ project }} exists"
  shell: bash -c "test \"$(echo $({{ ocadm }} get project | awk '{print $1}' | grep {{ project }}$ | wc -l))\" == \"1\" && echo true || echo false"
  register: project_exist
  
- fail:
    msg: "The project {{ project }} already exists"
  when: project_exist.stdout == "true"

- name: "Create project in Openshift"
  shell: "{{ ocadm }} new-project {{ project }}"
  when: project_exist.stdout == "false"

- name: "Giving rights to admin user on project we've just created"
  shell: "{{ ocadm }} adm policy add-role-to-user admin admin -n {{ project }}"
  when: project_exist.stdout == "false"

- name: Creates directory for templates
  file: path="{{ templates_dir }}" state=directory

- name: Copying templates of tools
  copy:
    src: "../../../../cicd/tools/{{ item }}"
    dest: "{{ templates_dir }}"
    force: yes
  with_items:
    - jenkins
    - gerrit
    - nexus
    - sonar

