---
bases:
  - envs/common.yaml
---
releases:

################################################################################
## External Secret Operator ####################################################
################################################################################

#
# References:
#   - https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets/values.yaml
#
- name: "external-secrets"
  namespace: "external-secrets"
  labels:
    chart: "external-secrets"
    repo: "external-secrets"
    component: "secrets"
    namespace: "external-secrets"
    vendor: "external-secrets-operator"
    default: "true"
  chart: "external-secrets/external-secrets"
  version: "0.8.3"
  wait: true
  installed: true
  values:
    - replicaCount: 1
