---
bases:
  - envs/common.yaml
---
releases:

#######################################################################################
## aerokube-moon
#######################################################################################

#
# References:
#   - https://github.com/aerokube/charts
#
- name: "moon"
  namespace: "moon"
  labels:
    chart: "aerokube/moon"
    repo: "prometheus-msteams"
    component: "moon"
    namespace: "moon"
    vendor: "aerokube"
    default: "true"
  chart: "moon/moon2"
  version: "2.4.4"
  wait: true
  values:
    - replicas: 1
      service:
        type: NodePort
      ingress:
        {{- if eq .Values.global.platform "openshift" }}
        openshift: true
        {{- end }}
        host: moon.{{ .Values.global.dnsWildCard }}
