apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  generation: 17
  labels:
    app: petclinic-frontend
  name: petclinic-frontend
spec:
  replicas: 1
  selector:
    deploymentconfig: petclinic-frontend
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petclinic-frontend
        deploymentconfig: petclinic-frontend
    spec:
      containers:
        - env:
            - name: BACKEND
              value: 'http://petclinic-backend.10.17.129.14.xip.io'
          imagePullPolicy: Always
          name: petclinic-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - petclinic-frontend
        from:
          kind: ImageStreamTag
          name: 'petclinic-frontend:latest'
          namespace: ci-cd
      type: ImageChange
    - type: ConfigChange
