---
environments:
  {{ .Environment.Name }}:
    values:
    - envs/{{ .Environment.Name }}.yaml
---
repositories:
- name: "ingress-nginx"
  url: "https://kubernetes.github.io/ingress-nginx"

- name: "codecentric"
  url: "https://codecentric.github.io/helm-charts"

- name: "epamedp"
  url: "https://epam.github.io/edp-helm-charts/stable"

- name: "argo"
  url: "https://argoproj.github.io/argo-helm"

- name: "external-secrets"
  url: "https://charts.external-secrets.io"

- name: "defectdojo"
  url: "https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts"

# ReportPortal helm charts:
# - "minio"
# - "rabbitmq"
# Keycloak helm chart:
# - "postgresql"
- name: "bitnami"
  url: "https://charts.bitnami.com/bitnami"

# ReportPortal helm chart:
# - "postgresql"
- name: "bitnami-archive"
  url: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"

# ReportPortal helm chart:
# - "elasticsearch"
- name: "elastic"
  url: "https://helm.elastic.co"

# ReportPortal helm chart:
# - "reportportal"
- name: "report-portal"
  url: "git+https://github.com/reportportal/kubernetes@reportportal?ref=master"

# Aerokube/Moon helm chart:
- name: "moon"
  url: "https://charts.aerokube.com"
---
helmDefaults:
  createNamespace: true
  timeout: 500
  atomic: true
