{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.manageEDPInstallSecrets .Values.global.nexusUrl -}}
{{- if ne (index .Values "nexus-operator" "enabled") true -}}
{{- $secretStore := include "edp-install.secretStoreName" . }}
{{- $awsSecretName := .Values.externalSecrets.manageEDPInstallSecretsName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-ci.user
spec:
  target:
    template:
      metadata:
        labels:
          app.edp.epam.com/secret-type: nexus
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStore }}
  data:
  - secretKey: username
    remoteRef:
      key: {{ $awsSecretName }}
      property: nexus-ci-user.username
  - secretKey: password
    remoteRef:
      key: {{ $awsSecretName }}
      property: nexus-ci-user.password
{{- end }}
{{- end }}
