{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.manageEDPInstallSecrets }}
{{- if ne .Values.global.gitProvider "gerrit" -}}
{{- $gitProvider := .Values.global.gitProvider }}
{{- $secretStore := include "edp-install.secretStoreName" . }}
{{- $awsSecretName := .Values.externalSecrets.manageEDPInstallSecretsName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-{{ $gitProvider }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStore }}
  data:
  - secretKey: token
    remoteRef:
      key: {{ $awsSecretName }}
      property: {{ $gitProvider }}-config.token
  - secretKey: id_rsa
    remoteRef:
      key: {{ $awsSecretName }}
      property: {{ $gitProvider }}-config.id_rsa
      decodingStrategy: Base64
  - secretKey: secretString
    remoteRef:
      key: {{ $awsSecretName }}
      property: {{ $gitProvider }}-config.secretString
{{- end }}
{{- end }}
