{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.manageEDPInstallSecrets -}}
{{- if ne (index .Values "sonar-operator" "enabled") true -}}
{{- $namespace := .Values.global.edpName }}
{{- $secretStore := include "edp-install.secretStoreName" . }}
{{- $awsSecretName := .Values.externalSecrets.manageEDPInstallSecretsName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonar-ciuser-token
  namespace: {{ $namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStore }}
  data:
  - secretKey: username
    remoteRef:
      key: {{ $awsSecretName }}
      property: sonar-ciuser-token.username
      decodingStrategy: Base64
  - secretKey: secret
    remoteRef:
      key: {{ $awsSecretName }}
      property: sonar-ciuser-token.secret
      decodingStrategy: Base64
{{- end }}
{{- end }}