{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.manageEDPInstallSecrets }}
{{- $secretStore := include "edp-install.secretStoreName" . }}
{{- $awsSecretName := .Values.externalSecrets.manageEDPInstallSecretsName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kaniko-docker-config
spec:
  target:
    template:
      metadata:
        labels:
          app.edp.epam.com/secret-type: registry
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .secretValue }}` }}"
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStore }}
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: {{ $awsSecretName }}
      property: kaniko-docker-config
    secretKey: secretValue
{{- end }}
