{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.manageEDPInstallSecrets -}}
{{- $secretStore := include "edp-install.secretStoreName" . }}
{{- $awsSecretName := .Values.externalSecrets.manageEDPInstallSecretsName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-sonarqube
spec:
  target:
    template:
      metadata:
        labels:
          app.edp.epam.com/secret-type: sonar
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStore }}
  data:
  - secretKey: token
    remoteRef:
      key: {{ $awsSecretName }}
      property: ci-sonarqube.token
  - secretKey: url
    remoteRef:
      key: {{ $awsSecretName }}
      property: ci-sonarqube.url
{{- end }}
