{{- if .Values.externalSecrets.enabled }}
{{- if eq .Values.externalSecrets.type "gcpsm" }}
{{- $gcpsmProjectID := .Values.externalSecrets.secretProvider.gcpsm.projectID }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "edp-install.secretStoreName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ $gcpsmProjectID }}
{{- end }}
{{- end }}
