{{- if not (lookup "v1" "ConfigMap" ".Values.global.edpName" "gt-template").metadata }}
apiVersion: v1
data:
  gt.json: |
            {
              "apiVersion": "v2.edp.epam.com/v1alpha1",
              "kind": "GitTag",
              "metadata": {
                "name": "replace"
              },
              "spec": {
                "codebase": "replace",
                "branch": "replace",
                "tag": "replace"
              }
            }
kind: ConfigMap
metadata:
  name: gt-template
{{end}}