{{- if .Values.sso.enabled -}}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClientScope
metadata:
  name: edp
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
spec:
  name: edp
  realm: main
  description: "default scope required for oauth2-proxy"
  protocol: openid-connect
  protocolMappers:
    - name: oauth2-proxy-audience
      protocol: openid-connect
      protocolMapper: "oidc-audience-mapper"
      config:
        "access.token.claim": "true"
        "included.client.audience": "oauth2-proxy"
{{ end }}
