{{- if .Values.sso.enabled -}}
apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: "main"
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
spec:
  url: {{ .Values.sso.keycloakUrl }}
  secret: "keycloak"
{{ end }}
