{{- if .Values.sso.enabled -}}
{{- if .Values.oauth2_proxy.enabled -}}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: oauth2-proxy
spec:
  advancedProtocolMappers: true
  clientId: oauth2-proxy
  directAccess: true
  public: false
  defaultClientScopes:
    - edp
  realmRef:
    kind: KeycloakRealm
    name: main
  webUrl: "https://{{ include "oauth2_proxy.Url" . }}"
{{ end }}
{{ end }}
