{{- if .Values.oauth2_proxy.enabled -}}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: oauth2-proxy
spec:
  advancedProtocolMappers: true
  clientId: oauth2-proxy
  directAccess: true
  public: false
  defaultClientScopes:
    - edp
  targetRealm: "{{ .Release.Namespace }}-main"
  webUrl: "https://{{ include "oauth2_proxy.Url" . }}"
{{ end }}
