{{- if .Values.sso.enabled -}}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: "main"
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
spec:
  keycloakOwner: main
  realmName: {{ .Release.Namespace }}-main
  ssoRealmEnabled: true
  ssoRealmName: {{ .Values.sso.realmName }}
  users:
  {{- range .Values.sso.admins }}
  - username: {{.}}
    realmRoles:
      - administrator
  {{- end}}
  {{- range .Values.sso.developers }}
  - username: {{.}}
    realmRoles:
      - developer
  {{- end}}
{{ end }}
