kind: Template
apiVersion: v1
metadata:
  name: sonar-integration
  annotations:
    description: |-
          The SonarQube template for intergation with Jenkins
    iconClass: icon-jenkins
    openshift.io/display-name: EDP Sonar-integration
    tags: ci-cd
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: sonar-integration
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: sonar-integration
      spec:
        initContainers:
        - name: init-jenkins
          image: busybox
          command: ["sh", "-c", "while ! nc -w 1 jenkins 8080 </dev/null; do echo waiting for jenkins; sleep 10; done;"]
        - name: init-sonar
          image: busybox
          command: ["sh", "-c", "while ! nc -w 1 sonar 9000 </dev/null; do echo waiting for sonar; sleep 10; done;"]
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - jenkins
              topologyKey: kubernetes.io/hostname
        containers:
        - image: python:3.6-alpine
          imagePullPolicy: IfNotPresent
          name: sonar-integration
          command: ["/bin/sh","-c","pip install requests && python /tmp/sonar/config.py"]
          env:
          - name: SONAR_HOST
            value: sonar
          - name: SONAR_PORT
            value: "9000"
          - name: SONAR_ADMIN
            value: admin
          - name: SONAR_PASSWORD
            value: admin
          - name: AUTO_USER
            value: jenkins
          - name: AUTO_USER_PASSWORD
            value: jenkins
          - name: APP_FILE
            value: "/tmp/config.py"
          volumeMounts:
          - mountPath: /tmp/sonar
            name: data
          - mountPath: /opt/data/jenkins
            name: jenkins-data
          - mountPath: /opt/data/sonar
            name: jenkins-data
        volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data
        - name: data
          configMap:
            defaultMode: 420
            name: sonar-integration
        restartPolicy: Never
        serviceAccount: sonar
