--- # Gerrit full installation
- name: "Give rights to gerrit account"
  shell: "{{ ocadm }} -n {{ project_cicd }} adm policy add-scc-to-user anyuid -z gerrit"

- name: "Install Gerrit app"
  command: |
    {{ ocadm }} -n {{ project_cicd }} new-app -f {{ templates_dir }}/gerrit/gerrit.yaml 
    -p GERRIT_VERSION={{ tools.gerrit.version }} 
    -p GERRIT_DB_SECRET=gerrit-db 
    -p GERRIT_DATA_CAPACITY={{ tools.gerrit.volume_capacity }} 
    -p GERRIT_DB_CAPACITY={{ tools.gerrit.volume_db_capacity }} 
    -p GERRIT_WEB_URL={{ tools.gerrit.web_url }}
  register: result
  ignore_errors: true
  changed_when: '"already" not in result.stderr'
  failed_when:
    - 'result.rc != 0'
    - '"already" not in result.stderr'

- name: "Install Gerrit-to-Jenkins integration"
  command: |
    {{ ocadm }} -n {{ project_cicd }} new-app -f {{ templates_dir }}/gerrit/gerrit-integration.yaml
    -p GERRIT_JOB_VERSION={{ tools.gerrit.job_version }}
  register: result
  ignore_errors: true
  changed_when: '"already" not in result.stderr'
  failed_when:
    - 'result.rc != 0'
    - '"already" not in result.stderr'
