---
- name: "Install docker via yum"
  tags:
    - docker_install
  yum:
    name: "{{ item }}"
    state: present
  when: ansible_pkg_mgr == 'yum'
  with_items:
    - "docker-{{ docker_version }}"

- name: "Install dependencies"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - python-pip
    - python-dev
  when: ansible_pkg_mgr == 'apt'


- name: "Add Docker repository and update apt cache"
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present
  when: ansible_pkg_mgr == 'apt'


- name: "Install docker package"
  apt:
    name: "{{ docker_pkg_name }}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ docker_apt_cache_valid_time }}"
  when: ansible_pkg_mgr == 'apt'

- name: "Install docker-py"
  pip:
    name: docker
    state: present
          